#ifndef	_LED7_DRV_H_
#define _LED7_DRV_H_

#if UI_ENABLE

#include "includes.h"

#ifdef SUPPORT_MUTE_FLASH
extern bool b_muteFlag;
#endif
#ifdef TEST_PANEL_LED
extern u8 bledComValue;
extern u8 bledGridValue;
#endif


#ifdef SUPPORT_HT1628_DRIVER
#ifdef USE_KEY_TO_CONTROL_HT1628_LIGHTS_ONOFF
extern bool ifRunTimer;
#endif
#define HT1628_CMD_MODE  0x02 //6grid-11seg
#define HT1628_CMD_WRITE 0x40  //cmd write data to ht1628
#define HT1628_CMD_SPEC_ADDR 0x44 //identify address cmd
#define HT1628_CMD_NORMAL_MODE 0x40 //normal mode cmd
#define HT1628_CMD_ADDR_SET  0xc0   //address set
#define HT1628_CMD_ON 0x88          //display on cmd
#define HT1628_CMD_OFF 0x80        //display off cmd

#ifdef HT1628_CLK_DATA_STB_USE_pb9pb7pb6
#define HT1628_IO_INIT() PORTB_DIR &=~(BIT(9)|BIT(7)|BIT(6));PORTB_PU&=~(BIT(9)|BIT(7)|BIT(6));\
                         PORTB_PD&=~(BIT(9)|BIT(7)|BIT(6))
#define HT1628_CLK(x) if(x){PORTB_OUT|=BIT(9);}else{PORTB_OUT&=~BIT(9);} 
#define HT1628_DATA(x) if(x){PORTB_OUT|=BIT(7);}else{PORTB_OUT&=~BIT(7);} 
#define HT1628_STB(x) if(x){PORTB_OUT|=BIT(6);}else{PORTB_OUT&=~BIT(6);} 
void ht1628_scan(void);
#endif
#endif

#if defined(SUPPORT_PT6312_MODE)
  #define HT1628_CMD_MODE  0x03 //6grid-11seg
  #define HT1628_CMD_WRITE 0x40  //cmd write data to ht1628
  #define HT1628_CMD_SPEC_ADDR 0x44 //identify address cmd
  #define HT1628_CMD_NORMAL_MODE 0x40 //normal mode cmd
  #define HT1628_CMD_ADDR_SET  0xc0   //address set
#ifdef PT6312_DATA_CLK_STB_USE_PA6PA4PA0
  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(6)|BIT(4)|BIT(0));PORTA_PU&=~(BIT(6)|BIT(4)|BIT(0));\
                           PORTA_PD&=~(BIT(6)|BIT(4)|BIT(0))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(4);}else{PORTA_OUT&=~BIT(4);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(0);}else{PORTA_OUT&=~BIT(0);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(6);}else{PORTA_OUT&=~BIT(6);} 
#endif

#elif defined(SUPPORT_HT1621C_MODE)

 void  WR_HT1621_DATA(u8 data,u8 cnt);
 void  HT1621_INIT(void);
 void  WR_HT1621_CMD(u8 cmd);
 void  WR_HT1621_ONE_DATA(u8 addr,u8 data);
 void  WR_HT1621_ALL_DATA(u8 addr,u8 *p,u8 cnt);


#define HT1621_CMD_SYSDIS_ON 0x02  // SYS DIS
#define HT1621_CMD_SYSDIS_OFF 0x00 // �ر�ϵͳ������LCD ƫѹ������
#define HT1621_CMD_LCD_ON 0x06 
#define HT1621_CMD_WDTDIS 0x0A 
#define HT1621_CMD_LCD_OFF 0x04
#define HT1621_CMD_MODE  0x52 // 0x50 // 1/2 bias   4com 
#define HT1621_CMD_RC_MODE 0x30  // inside rc ( 256_RC)

  /*
	io  init
	mode set
	rc
	sysdis on
	lcdon

  */
  
#ifdef HT1621_DATA_CLK_STB_USE_PA9PA8PA7
  #define HT1621_IO_INIT()  PORTA_DIE |= BIT(8);PORTA_DIR &=~(BIT(9)|BIT(7)|BIT(8)); //PORTA_PU|=(BIT(9)|BIT(7)|BIT(8));
							  
  #define HT1621_CLK(x) if(x){PORTA_OUT&=~BIT(8);}else{PORTA_OUT&=~BIT(8);} 
  #define HT1621_DATA(x) if(x){PORTA_OUT|=BIT(9);}else{PORTA_OUT&=~BIT(9);} 
  #define HT1621_STB(x) if(x){PORTA_OUT|=BIT(7);}else{PORTA_OUT&=~BIT(7);}   
#endif

#elif defined(SUPPORT_TM1628_MODE)
  #define HT1628_CMD_MODE  0x03 //6grid-11seg
  #define HT1628_CMD_WRITE 0x40  //cmd write data to ht1628
  #define HT1628_CMD_SPEC_ADDR 0x44 //identify address cmd
  #define HT1628_CMD_NORMAL_MODE 0x40 //normal mode cmd
  #define HT1628_CMD_ADDR_SET  0xc0   //address set
#ifdef TM1628_DATA_CLK_STB_USE_PB7PB6PB9
  #define HT1628_IO_INIT() PORTB_DIR &=~(BIT(9)|BIT(7)|BIT(6));PORTB_PU&=~(BIT(9)|BIT(7)|BIT(6));\
                           PORTB_PD&=~(BIT(9)|BIT(7)|BIT(6))
  #define HT1628_CLK(x) if(x){PORTB_OUT|=BIT(6);}else{PORTB_OUT&=~BIT(6);} 
  #define HT1628_DATA(x) if(x){PORTB_OUT|=BIT(7);}else{PORTB_OUT&=~BIT(7);} 
  #define HT1628_STB(x) if(x){PORTB_OUT|=BIT(9);}else{PORTB_OUT&=~BIT(9);} 
#elif defined(TM1628_DATA_CLK_STB_USE_PB10PB9PA0)
  #define HT1628_IO_INIT() PORTB_DIR &=~(BIT(10)|BIT(9));PORTB_PU&=~(BIT(10)|BIT(9));\
							 PORTB_PD&=~(BIT(10)|BIT(9));\
							 PORTA_DIR &=~(BIT(0));PORTA_PU&=~(BIT(0));\
							 PORTA_PD&=~(BIT(0))
  #define HT1628_CLK(x) if(x){PORTB_OUT|=BIT(9);}else{PORTB_OUT&=~BIT(9);} 
  #define HT1628_DATA(x) if(x){PORTB_OUT|=BIT(10);}else{PORTB_OUT&=~BIT(10);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(0);}else{PORTA_OUT&=~BIT(0);}   
#elif defined(TM1628_DATA_CLK_STB_USE_PB8PB7PB6)
  #define HT1628_IO_INIT() PORTB_DIR &=~(BIT(8)|BIT(7)|BIT(6));PORTB_PU&=~(BIT(8)|BIT(7)|BIT(6));\
                           PORTB_PD&=~(BIT(8)|BIT(7)|BIT(6))
  #define HT1628_CLK(x) if(x){PORTB_OUT|=BIT(7);}else{PORTB_OUT&=~BIT(7);} 
  #define HT1628_DATA(x) if(x){PORTB_OUT|=BIT(8);}else{PORTB_OUT&=~BIT(8);} 
  #define HT1628_STB(x) if(x){PORTB_OUT|=BIT(6);}else{PORTB_OUT&=~BIT(6);} 
#elif defined(TM1628_DATA_CLK_STB_USE_PB10PB9PB8)
  #define HT1628_IO_INIT() PORTB_DIR &=~(BIT(10)|BIT(9)|BIT(8));PORTB_PU&=~(BIT(10)|BIT(9)|BIT(8));\
                           PORTB_PD&=~(BIT(10)|BIT(9)|BIT(8))
  #define HT1628_CLK(x) if(x){PORTB_OUT|=BIT(9);}else{PORTB_OUT&=~BIT(9);} 
  #define HT1628_DATA(x) if(x){PORTB_OUT|=BIT(10);}else{PORTB_OUT&=~BIT(10);} 
  #define HT1628_STB(x) if(x){PORTB_OUT|=BIT(8);}else{PORTB_OUT&=~BIT(8);} 
  
#elif defined(TM1628_DATA_CLK_STB_USE_PA6PA7PA8)

  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(6)|BIT(7)|BIT(8));PORTA_PU&=~(BIT(6)|BIT(7)|BIT(8));\
							   PORTA_PD&=~(BIT(6)|BIT(7)|BIT(8))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(7);}else{PORTA_OUT&=~BIT(7);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(6);}else{PORTA_OUT&=~BIT(6);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(8);}else{PORTA_OUT&=~BIT(8);}   

#elif defined(TM1628_DATA_CLK_STB_USE_PA4P14P15)

  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(4)|BIT(14)|BIT(15));PORTA_PU&=~(BIT(4)|BIT(14)|BIT(15));\
							   PORTA_PD&=~(BIT(4)|BIT(14)|BIT(15))
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(4);}else{PORTA_OUT&=~BIT(4);} 
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(14);}else{PORTA_OUT&=~BIT(14);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(15);}else{PORTA_OUT&=~BIT(15);} 
  
   #ifdef SUPPORT_TM1628_KEY_READ
   #define HT1628_DATA_IN()   PORTA_DIR|=BIT(4);PORTA_PU|=BIT(4)
   #define HT1628_DATA_OUT()	PORTA_DIR&=~BIT(4)
   #define HT1628_DATA_READ() PORTA_IN&BIT(4)
   #endif

#elif defined(TM1628_DATA_CLK_STB_USE_PA9PA8PA7)
  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(9)|BIT(7)|BIT(8));PORTA_PU&=~(BIT(9)|BIT(7)|BIT(8));\
							   PORTA_PD&=~(BIT(9)|BIT(7)|BIT(8))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(8);}else{PORTA_OUT&=~BIT(8);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(9);}else{PORTA_OUT&=~BIT(9);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(7);}else{PORTA_OUT&=~BIT(7);}   
#elif defined(TM1628_DATA_CLK_STB_USE_PA15PA14PA11)
  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(11)|BIT(14)|BIT(15));PORTA_PU&=~(BIT(11)|BIT(14)|BIT(15));\
                           PORTA_PD&=~(BIT(11)|BIT(14)|BIT(15))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(14);}else{PORTA_OUT&=~BIT(14);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(15);}else{PORTA_OUT&=~BIT(15);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(11);}else{PORTA_OUT&=~BIT(11);} 
#elif defined(TM1628_DATA_CLK_STB_USE_PA15PA14PA10)
  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(10)|BIT(14)|BIT(15));PORTA_PU&=~(BIT(10)|BIT(14)|BIT(15));\
                           PORTA_PD&=~(BIT(10)|BIT(14)|BIT(15))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(14);}else{PORTA_OUT&=~BIT(14);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(15);}else{PORTA_OUT&=~BIT(15);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(10);}else{PORTA_OUT&=~BIT(10);} 
  
#elif defined(TM1628_DATA_CLK_STB_USE_PA11PA14PA15)
  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(11)|BIT(14)|BIT(15));PORTA_PU&=~(BIT(11)|BIT(14)|BIT(15));\
							 PORTA_PD&=~(BIT(11)|BIT(14)|BIT(15))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(14);}else{PORTA_OUT&=~BIT(14);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(11);}else{PORTA_OUT&=~BIT(11);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(15);}else{PORTA_OUT&=~BIT(15);} 
#elif defined(TM1628_DATA_CLK_STB_USE_PA10PA14PA15)
  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(10)|BIT(14)|BIT(15));PORTA_PU&=~(BIT(10)|BIT(14)|BIT(15));\
							   PORTA_PD&=~(BIT(10)|BIT(14)|BIT(15))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(14);}else{PORTA_OUT&=~BIT(14);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(10);}else{PORTA_OUT&=~BIT(10);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(15);}else{PORTA_OUT&=~BIT(15);} 
#elif defined(TM1628_DATA_CLK_STB_USE_PA8PA7PA6)
  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(8)|BIT(7)|BIT(6));PORTA_PU&=~(BIT(8)|BIT(7)|BIT(6));\
							 PORTA_PD&=~(BIT(8)|BIT(7)|BIT(6))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(7);}else{PORTA_OUT&=~BIT(7);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(8);}else{PORTA_OUT&=~BIT(8);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(6);}else{PORTA_OUT&=~BIT(6);} 
#elif defined(TM1628_DATA_CLK_STB_USE_PA9PA7PA6)
  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(9)|BIT(7)|BIT(6));PORTA_PU&=~(BIT(9)|BIT(7)|BIT(6));\
  						   PORTA_PD&=~(BIT(9)|BIT(7)|BIT(6))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(7);}else{PORTA_OUT&=~BIT(7);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(9);}else{PORTA_OUT&=~BIT(9);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(6);}else{PORTA_OUT&=~BIT(6);} 
#elif defined(TM1628_DATA_CLK_STB_USE_PA7PA6PA4)
  #define HT1628_IO_INIT() PORTA_DIR &=~(BIT(7)|BIT(6)|BIT(4));PORTA_PU&=~(BIT(7)|BIT(6)|BIT(4));\
  						   PORTA_PD&=~(BIT(7)|BIT(6)|BIT(4))
  #define HT1628_CLK(x) if(x){PORTA_OUT|=BIT(6);}else{PORTA_OUT&=~BIT(6);} 
  #define HT1628_DATA(x) if(x){PORTA_OUT|=BIT(7);}else{PORTA_OUT&=~BIT(7);} 
  #define HT1628_STB(x) if(x){PORTA_OUT|=BIT(4);}else{PORTA_OUT&=~BIT(4);}   
  
#endif
#elif defined(LED_12PIN_MODE)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						 PORTA_OUT &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						 PORTA_PD &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						 PORTA_PU &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                         PORTB_DIR |= (BIT(6)|BIT(7)|BIT(8)|BIT(9));\
                         PORTB_OUT &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9));\
                         PORTB_PD &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9));\
                         PORTB_PU &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9))
                         
  #define LED_SET_PIN1(x) if(x){PORTB_OUT|=BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU|=BIT(6);PORTB_PD&=~BIT(6);}else{PORTB_OUT&=~BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU&=~BIT(6);PORTB_PD|=BIT(6);}
  #define LED_SET_PIN2(x) if(x){PORTB_OUT|=BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU|=BIT(7);PORTB_PD&=~BIT(7);}else{PORTB_OUT&=~BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU&=~BIT(7);PORTB_PD|=BIT(7);}
  #define LED_SET_PIN3(x) if(x){PORTB_OUT|=BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU|=BIT(8);PORTB_PD&=~BIT(8);}else{PORTB_OUT&=~BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU&=~BIT(8);PORTB_PD|=BIT(8);}
  #define LED_SET_PIN4(x) if(x){PORTB_OUT|=BIT(9);PORTB_DIR&=~BIT(9);PORTB_PU|=BIT(9);PORTB_PD&=~BIT(9);}else{PORTB_OUT&=~BIT(9);PORTB_DIR&=~BIT(9);PORTB_PU&=~BIT(9);PORTB_PD|=BIT(9);}
  #define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}
  #define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
  #define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU|=BIT(8);PORTA_PD&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU&=~BIT(8);PORTA_PD|=BIT(8);}
  #define LED_SET_PIN8(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
  #define LED_SET_PIN9(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
  #define LED_SET_PIN10(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
  #define LED_SET_PIN11(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
  #define LED_SET_PIN12(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#elif defined(LED_13PIN_MODE)
  #ifdef LED_USE_13PIN_COMpb6pb9pb10pa8pa7pa15_SEGpa14pb7pa10pa9pa11pb8pa6
    #define LED_INIT_PIN() PORTA_DIR |= (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						   PORTA_OUT &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						   PORTA_PD &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						   PORTA_PU &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						   PORTB_DIR |= (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10));\
						   PORTB_OUT &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10));\
						   PORTB_PD &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10));\
						   PORTB_PU &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10))

    #define LED_SET_COM1(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
    #define LED_SET_COM2(x) if(x){PORTB_OUT|=BIT(10);PORTB_DIR&=~BIT(10);PORTB_PU|=BIT(10);PORTB_PD&=~BIT(10);}else{PORTB_OUT&=~BIT(10);PORTB_DIR&=~BIT(10);PORTB_PU&=~BIT(10);PORTB_PD|=BIT(10);}
    #define LED_SET_COM3(x) if(x){PORTB_OUT|=BIT(9);PORTB_DIR&=~BIT(9);PORTB_PU|=BIT(9);PORTB_PD&=~BIT(9);}else{PORTB_OUT&=~BIT(9);PORTB_DIR&=~BIT(9);PORTB_PU&=~BIT(9);PORTB_PD|=BIT(9);}
    #define LED_SET_COM4(x) if(x){PORTB_OUT|=BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU|=BIT(8);PORTB_PD&=~BIT(8);}else{PORTB_OUT&=~BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU&=~BIT(8);PORTB_PD|=BIT(8);}
    #define LED_SET_COM5(x) if(x){PORTB_OUT|=BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU|=BIT(7);PORTB_PD&=~BIT(7);}else{PORTB_OUT&=~BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU&=~BIT(7);PORTB_PD|=BIT(7);}
    #define LED_SET_COM6(x) if(x){PORTB_OUT|=BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU|=BIT(6);PORTB_PD&=~BIT(6);}else{PORTB_OUT&=~BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU&=~BIT(6);PORTB_PD|=BIT(6);}
    
    #define LED_SET_SEG1(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}
    #define LED_SET_SEG2(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
    #define LED_SET_SEG3(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
    #define LED_SET_SEG4(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
    #define LED_SET_SEG5(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
    #define LED_SET_SEG6(x) if(x){PORTA_OUT|=BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU|=BIT(8);PORTA_PD&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU&=~BIT(8);PORTA_PD|=BIT(8);}
    #define LED_SET_SEG7(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#elif defined LED_USE_13PIN_COMpb9876pa15pa14_SEGpa11pa10pa9pa5pa6pa7pa8

    #define LED_INIT_PIN() PORTA_DIR |= (BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						   PORTA_OUT &=~ (BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						   PORTA_PD &=~ (BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						   PORTA_PU &=~ (BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
						   PORTB_DIR |= (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10));\
						   PORTB_OUT &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9));\
						   PORTB_PD &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9));\
						   PORTB_PU &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9))
						   
    #define LED_SET_COM6(x) if(x){PORTB_OUT|=BIT(9);PORTB_DIR&=~BIT(9);PORTB_PU|=BIT(9);PORTB_PD&=~BIT(9);}else{PORTB_OUT&=~BIT(9);PORTB_DIR&=~BIT(9);PORTB_PU&=~BIT(9);PORTB_PD|=BIT(9);}
    #define LED_SET_COM5(x) if(x){PORTB_OUT|=BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU|=BIT(8);PORTB_PD&=~BIT(8);}else{PORTB_OUT&=~BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU&=~BIT(8);PORTB_PD|=BIT(8);}
    #define LED_SET_COM4(x) if(x){PORTB_OUT|=BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU|=BIT(7);PORTB_PD&=~BIT(7);}else{PORTB_OUT&=~BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU&=~BIT(7);PORTB_PD|=BIT(7);}
    #define LED_SET_COM3(x) if(x){PORTB_OUT|=BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU|=BIT(6);PORTB_PD&=~BIT(6);}else{PORTB_OUT&=~BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU&=~BIT(6);PORTB_PD|=BIT(6);}
    #define LED_SET_COM2(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
    #define LED_SET_COM1(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}


    #define LED_SET_SEG1(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_HD|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_HD&=~BIT(11);PORTA_PD|=BIT(11);}
    #define LED_SET_SEG2(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_HD|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_HD&=~BIT(10);PORTA_PD|=BIT(10);}
    #define LED_SET_SEG3(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_HD|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_HD&=~BIT(6);PORTA_PD|=BIT(6);}
    #define LED_SET_SEG4(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_HD|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_HD&=~BIT(7);PORTA_PD|=BIT(7);}
    #define LED_SET_SEG5(x) if(x){PORTA_OUT|=BIT(5);PORTA_DIR&=~BIT(5);PORTA_HD|=BIT(5);PORTA_PD&=~BIT(5);}else{PORTA_OUT&=~BIT(5);PORTA_DIR&=~BIT(5);PORTA_HD&=~BIT(5);PORTA_PD|=BIT(5);}   
    #define LED_SET_SEG6(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_HD|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_HD&=~BIT(9);PORTA_PD|=BIT(9);}
     #define LED_SET_SEG7(x) if(x){PORTA_OUT|=BIT(8);PORTA_DIR&=~BIT(8);PORTA_HD|=BIT(8);PORTA_PD&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);PORTA_HD&=~BIT(8);PORTA_PD|=BIT(8);}


  #endif
#elif defined(LED_7PIN_MODE)
#ifdef LED_USE_7PIN_PA7__PA11PA14PA15
#define LED_INIT_PIN() PORTA_DIR |= (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
	                   PORTA_OUT &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_PD &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_PU &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_HD &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15))
                       
#ifdef LED_7PIN_REVERSE
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(7);PORTA_PD &=~BIT(7);PORTA_HD|=BIT(7);PORTA_DIR&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(8);PORTA_PD &=~BIT(8);PORTA_HD|=BIT(8);PORTA_DIR&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(9);PORTA_PD &=~BIT(9);PORTA_HD|=BIT(9);PORTA_DIR&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(10);PORTA_PD &=~BIT(10);PORTA_HD|=BIT(10);PORTA_DIR&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(11);PORTA_PD &=~BIT(11);PORTA_HD|=BIT(11);PORTA_DIR&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(14);PORTA_PD &=~BIT(14);PORTA_HD|=BIT(14);PORTA_DIR&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);}
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(15);PORTA_PD &=~BIT(15);PORTA_HD|=BIT(15);PORTA_DIR&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);}
#else
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(7);PORTA_PU|=BIT(7);PORTA_HD|=BIT(7);PORTA_DIR&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(8);PORTA_PU|=BIT(8);PORTA_HD|=BIT(8);PORTA_DIR&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(9);PORTA_PU|=BIT(9);PORTA_HD|=BIT(9);PORTA_DIR&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(10);PORTA_PU|=BIT(10);PORTA_HD|=BIT(10);PORTA_DIR&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(11);PORTA_PU|=BIT(11);PORTA_HD|=BIT(11);PORTA_DIR&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(14);PORTA_PU|=BIT(14);PORTA_HD|=BIT(14);PORTA_DIR&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(15);PORTA_PU|=BIT(15);PORTA_HD|=BIT(15);PORTA_DIR&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);}
#endif
#elif defined(LED_USE_7PIN_PA4PA6PA7PA8PA9PA10PA11)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(4)|BIT(6));\
	                   PORTA_OUT &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(4)|BIT(6));\
                       PORTA_PD &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(4)|BIT(6));\
                       PORTA_PU &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(4)|BIT(6));\
                       PORTA_HD &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(4)|BIT(6))
#ifdef LED_7PIN_REVERSE
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(4);PORTA_PU|=BIT(4);PORTA_HD|=BIT(4);PORTA_DIR&=~BIT(4);}else{PORTA_OUT&=~BIT(4);PORTA_DIR&=~BIT(4);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(6);PORTA_PU|=BIT(6);PORTA_HD|=BIT(6);PORTA_DIR&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(7);PORTA_PU|=BIT(7);PORTA_HD|=BIT(7);PORTA_DIR&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(8);PORTA_PU|=BIT(8);PORTA_HD|=BIT(8);PORTA_DIR&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(9);PORTA_PU|=BIT(9);PORTA_HD|=BIT(9);PORTA_DIR&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(10);PORTA_PU|=BIT(10);PORTA_HD|=BIT(10);PORTA_DIR&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);}
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(11);PORTA_PU|=BIT(11);PORTA_HD|=BIT(11);PORTA_DIR&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);}
#else
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(4);PORTA_PU|=BIT(4);PORTA_HD|=BIT(4);PORTA_DIR&=~BIT(4);}else{PORTA_OUT&=~BIT(4);PORTA_DIR&=~BIT(4);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(6);PORTA_PU|=BIT(6);PORTA_HD|=BIT(6);PORTA_DIR&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(7);PORTA_PU|=BIT(7);PORTA_HD|=BIT(7);PORTA_DIR&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(8);PORTA_PU|=BIT(8);PORTA_HD|=BIT(8);PORTA_DIR&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(9);PORTA_PU|=BIT(9);PORTA_HD|=BIT(9);PORTA_DIR&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(10);PORTA_PU|=BIT(10);PORTA_HD|=BIT(10);PORTA_DIR&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(11);PORTA_PU|=BIT(11);PORTA_HD|=BIT(11);PORTA_DIR&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);}
#endif
#elif defined(LED_USE_7PIN_PA15PA11_PA6)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
	                   PORTA_OUT &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
                       PORTA_PD &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
                       PORTA_PU &=~ (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
	                   PORTA_HD |= (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(15))
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU|=BIT(8);PORTA_PD&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU&=~BIT(8);PORTA_PD|=BIT(8);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}

#elif defined(support_LED7_USER_PA14PA11PA10PA8PA5PA3PA2)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(2)|BIT(3)|BIT(5)|BIT(8)|BIT(10)|BIT(11)|BIT(14));\
									PORTA_OUT &=~ (BIT(2)|BIT(3)|BIT(5)|BIT(8)|BIT(10)|BIT(11)|BIT(14));\
									PORTA_PD &=~ (BIT(2)|BIT(3)|BIT(5)|BIT(8)|BIT(10)|BIT(11)|BIT(14));\
									PORTA_PU &=~ (BIT(2)|BIT(3)|BIT(5)|BIT(8)|BIT(10)|BIT(11)|BIT(14));\
									PORTA_HD  &=~ (BIT(2)|BIT(3)|BIT(5)|BIT(8)|BIT(10)|BIT(11)|BIT(14))


#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_HD|=BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_HD|=BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_HD|=BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(8);PORTA_DIR&=~BIT(8);PORTA_HD|=BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(5);PORTA_DIR&=~BIT(5);PORTA_HD|=BIT(5);}else{PORTA_OUT&=~BIT(5);PORTA_DIR&=~BIT(5);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(3);PORTA_DIR&=~BIT(3);PORTA_HD|=BIT(3);}else{PORTA_OUT&=~BIT(3);PORTA_DIR&=~BIT(3);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(2);PORTA_DIR&=~BIT(2);PORTA_HD|=BIT(2);}else{PORTA_OUT&=~BIT(2);PORTA_DIR&=~BIT(2);}

#elif defined(LED_USE_7PIN_PA6PA7_PA9PA10PA4PA14PA15)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(4)|BIT(14)|BIT(15));\
                       PORTA_OUT &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(4)|BIT(14)|BIT(15));\
                       PORTA_PD &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(4)|BIT(14)|BIT(15));\
                       PORTA_PU &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(4)|BIT(14)|BIT(15));\
	                   PORTA_HD  &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(4)|BIT(14)|BIT(15))
                       
#ifdef LED_7PIN_REVERSE
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_HD|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_HD|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_HD|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_HD|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(4);PORTA_DIR&=~BIT(4);PORTA_HD|=BIT(4);PORTA_PD&=~BIT(4);}else{PORTA_OUT&=~BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU&=~BIT(4);PORTA_PD|=BIT(4);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_HD|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_HD|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#else
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_HD|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_HD|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_HD|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_HD|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(4);PORTA_DIR&=~BIT(4);PORTA_HD|=BIT(4);PORTA_PD&=~BIT(4);}else{PORTA_OUT&=~BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU&=~BIT(4);PORTA_PD|=BIT(4);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_HD|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_HD|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#endif


#elif defined(LED_USE_7PIN_PA6PA7_PA9PA10PA11PA14PA15)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_OUT &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_PD &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_PU &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
	                   PORTA_HD  &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15))
                       
#ifdef LED_7PIN_REVERSE
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_HD|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_HD|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_HD|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_HD|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_HD|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_HD|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_HD|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#else
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_HD|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_HD|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_HD|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_HD|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_HD|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_HD|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_HD|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#endif
#elif defined(LED_USE_7PIN_PA15PA14PA4PA10PA9PA7PA6)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(4)|BIT(14)|BIT(15));\
    	               PORTA_OUT &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(4)|BIT(14)|BIT(15));\
                       PORTA_PD &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(4)|BIT(14)|BIT(15));\
                       PORTA_PU &=~ (BIT(7)|BIT(6)|BIT(9)|BIT(10)|BIT(4)|BIT(14)|BIT(15))

#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU|=BIT(4);PORTA_PD&=~BIT(4);}else{PORTA_OUT&=~BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU&=~BIT(4);PORTA_PD|=BIT(4);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#elif defined(LED_USE_7PIN_PB8PB7PB6PA15PA14PA10PA9)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(9)|BIT(10)|BIT(14)|BIT(15));\
	                   PORTA_OUT &=~ (BIT(9)|BIT(10)|BIT(14)|BIT(15));\
                       PORTA_PD &=~ (BIT(9)|BIT(10)|BIT(14)|BIT(15));\
                       PORTA_PU &=~ (BIT(9)|BIT(10)|BIT(14)|BIT(15));\
                       PORTB_DIR |= (BIT(8)|BIT(7)|BIT(6));\
	                   PORTB_OUT &=~ (BIT(8)|BIT(7)|BIT(6));\
                       PORTB_PD &=~ (BIT(8)|BIT(7)|BIT(6));\
                       PORTB_PU &=~ (BIT(8)|BIT(7)|BIT(6))
                       
#define LED_SET_PIN1(x) if(x){PORTB_OUT|=BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU|=BIT(8);PORTB_PD&=~BIT(8);}else{PORTB_OUT&=~BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU&=~BIT(8);PORTB_PD|=BIT(8);}
#define LED_SET_PIN2(x) if(x){PORTB_OUT|=BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU|=BIT(7);PORTB_PD&=~BIT(7);}else{PORTB_OUT&=~BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU&=~BIT(7);PORTB_PD|=BIT(7);}
#define LED_SET_PIN3(x) if(x){PORTB_OUT|=BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU|=BIT(6);PORTB_PD&=~BIT(6);}else{PORTB_OUT&=~BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU&=~BIT(6);PORTB_PD|=BIT(6);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}                       
#elif defined(LED_USE_7PIN_PA9__PA15PB6PA7)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
	                   PORTA_OUT &=~ (BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_PD &=~ (BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_PU &=~ (BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTB_DIR |= (BIT(6));\
	                   PORTB_OUT &=~ (BIT(6));\
                       PORTB_PD &=~ (BIT(6));\
                       PORTB_PU &=~ (BIT(6))
                       
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#define LED_SET_PIN6(x) if(x){PORTB_OUT|=BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU|=BIT(6);PORTB_PD&=~BIT(6);}else{PORTB_OUT&=~BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU&=~BIT(6);PORTB_PD|=BIT(6);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#elif defined(LED_USE_7PIN_PA9__PA15PB6PB7)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_OUT &=~ (BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
	                   PORTA_PD &=~ (BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTA_PU &=~ (BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(15));\
                       PORTB_DIR |= (BIT(6)|BIT(7));\
	                   PORTB_OUT &=~ (BIT(6)|BIT(7));\
                       PORTB_PD &=~ (BIT(6)|BIT(7));\
                       PORTB_PU &=~ (BIT(6)|BIT(7))
                       
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#define LED_SET_PIN6(x) if(x){PORTB_OUT|=BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU|=BIT(6);PORTB_PD&=~BIT(6);}else{PORTB_OUT&=~BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU&=~BIT(6);PORTB_PD|=BIT(6);}
#define LED_SET_PIN7(x) if(x){PORTB_OUT|=BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU|=BIT(7);PORTB_PD&=~BIT(7);}else{PORTB_OUT&=~BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU&=~BIT(7);PORTB_PD|=BIT(7);}
#elif defined(LED_USE_7PIN_PA9PA10PB7PB8PA15PB6PA7)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(7)|BIT(9)|BIT(10)|BIT(15));\
                       PORTA_OUT &=~ (BIT(7)|BIT(9)|BIT(10)|BIT(15));\
	                   PORTA_PD &=~ (BIT(7)|BIT(9)|BIT(10)|BIT(15));\
                       PORTA_PU &=~ (BIT(7)|BIT(9)|BIT(10)|BIT(15));\
                       PORTB_DIR |= (BIT(6)|BIT(7)|BIT(8));\
                       PORTB_OUT &=~ (BIT(6)|BIT(7)|BIT(8));\
	                   PORTB_PD &=~ (BIT(6)|BIT(7)|BIT(8));\
                       PORTB_PU &=~ (BIT(6)|BIT(7)|BIT(8))
#ifdef LED_7PIN_REVERSE
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN5(x) if(x){PORTB_OUT|=BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU|=BIT(7);PORTB_PD&=~BIT(7);}else{PORTB_OUT&=~BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU&=~BIT(7);PORTB_PD|=BIT(7);}
#define LED_SET_PIN4(x) if(x){PORTB_OUT|=BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU|=BIT(8);PORTB_PD&=~BIT(8);}else{PORTB_OUT&=~BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU&=~BIT(8);PORTB_PD|=BIT(8);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#define LED_SET_PIN2(x) if(x){PORTB_OUT|=BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU|=BIT(6);PORTB_PD&=~BIT(6);}else{PORTB_OUT&=~BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU&=~BIT(6);PORTB_PD|=BIT(6);}
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#else                      
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN3(x) if(x){PORTB_OUT|=BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU|=BIT(7);PORTB_PD&=~BIT(7);}else{PORTB_OUT&=~BIT(7);PORTB_DIR&=~BIT(7);PORTB_PU&=~BIT(7);PORTB_PD|=BIT(7);}
#define LED_SET_PIN4(x) if(x){PORTB_OUT|=BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU|=BIT(8);PORTB_PD&=~BIT(8);}else{PORTB_OUT&=~BIT(8);PORTB_DIR&=~BIT(8);PORTB_PU&=~BIT(8);PORTB_PD|=BIT(8);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#define LED_SET_PIN6(x) if(x){PORTB_OUT|=BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU|=BIT(6);PORTB_PD&=~BIT(6);}else{PORTB_OUT&=~BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU&=~BIT(6);PORTB_PD|=BIT(6);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#endif
#elif defined(LED_USE_7PIN_PA10__PA6PA4PB6)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(4)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10));\
                       PORTA_OUT &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10));\
	                   PORTA_PD &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10));\
                       PORTA_PU &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10));\
                       PORTB_DIR |= (BIT(6));\
                       PORTB_OUT &=~ (BIT(6));\
	                   PORTB_PD &=~ (BIT(6));\
                       PORTB_PU &=~ (BIT(6))
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU|=BIT(8);PORTA_PD&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU&=~BIT(8);PORTA_PD|=BIT(8);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU|=BIT(4);PORTA_PD&=~BIT(4);}else{PORTA_OUT&=~BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU&=~BIT(4);PORTA_PD|=BIT(4);}
#define LED_SET_PIN7(x) if(x){PORTB_OUT|=BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU|=BIT(6);PORTB_PD&=~BIT(6);}else{PORTB_OUT&=~BIT(6);PORTB_DIR&=~BIT(6);PORTB_PU&=~BIT(6);PORTB_PD|=BIT(6);}

#elif defined(LED_USE_7PIN_PA6__PA11PA14)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(6));\
                       PORTA_OUT &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(6));\
	                   PORTA_PD &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(6));\
                       PORTA_PU &=~ (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(14)|BIT(6))                      
#ifdef LED_7PIN_REVERSE
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(8);PORTA_DIR&=~BIT(8);PORTA_PD&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);PORTA_PD|=BIT(8);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PD|=BIT(11);}
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PD|=BIT(14);}
#else
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU|=BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PU&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU|=BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PU&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU|=BIT(8);PORTA_PD&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU&=~BIT(8);PORTA_PD|=BIT(8);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU|=BIT(14);PORTA_PD&=~BIT(14);}else{PORTA_OUT&=~BIT(14);PORTA_DIR&=~BIT(14);PORTA_PU&=~BIT(14);PORTA_PD|=BIT(14);}
#endif
#elif defined(LED_USE_7PIN_PA4PA6PA7PA9PA10PA11PA15)
#ifdef LED_7PIN_REVERSE
#define LED_INIT_PIN() PORTA_DIR |= (BIT(4)|BIT(6)|BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
                       PORTA_OUT &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
	                   PORTA_PD &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
                       PORTA_PU &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(15))                      

#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU|=BIT(4);PORTA_PD&=~BIT(4);}else{PORTA_OUT&=~BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU&=~BIT(4);PORTA_PD|=BIT(4);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}

#else
#define LED_INIT_PIN() PORTA_DIR |= (BIT(4)|BIT(6)|BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
                       PORTA_OUT &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
	                   PORTA_PD &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(15));\
                       PORTA_PU &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(9)|BIT(10)|BIT(11)|BIT(15))                      

#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU|=BIT(4);PORTA_PD&=~BIT(4);}else{PORTA_OUT&=~BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU&=~BIT(4);PORTA_PD|=BIT(4);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU|=BIT(15);PORTA_PD&=~BIT(15);}else{PORTA_OUT&=~BIT(15);PORTA_DIR&=~BIT(15);PORTA_PU&=~BIT(15);PORTA_PD|=BIT(15);}
#endif
#elif defined(LED_USE_7PIN_PA4PA6_PA11)
#define LED_INIT_PIN() PORTA_DIR |= (BIT(4)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11));\
                       PORTA_OUT &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11));\
	                   PORTA_PD &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11));\
                       PORTA_PU &=~ (BIT(4)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11));\
                  	   PORTA_HD|= (BIT(4)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11))					   

#define LED_SET_PIN1(x) if(x){PORTA_OUT|=BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU|=BIT(4);PORTA_PD&=~BIT(4);}else{PORTA_OUT&=~BIT(4);PORTA_DIR&=~BIT(4);PORTA_PU&=~BIT(4);PORTA_PD|=BIT(4);}
#define LED_SET_PIN2(x) if(x){PORTA_OUT|=BIT(6);PORTA_DIR&=~BIT(6);PORTA_PD&=~BIT(6);}else{PORTA_OUT&=~BIT(6);PORTA_DIR&=~BIT(6);PORTA_PD|=BIT(6);}
#define LED_SET_PIN3(x) if(x){PORTA_OUT|=BIT(7);PORTA_DIR&=~BIT(7);PORTA_PD&=~BIT(7);}else{PORTA_OUT&=~BIT(7);PORTA_DIR&=~BIT(7);PORTA_PD|=BIT(7);}
#define LED_SET_PIN4(x) if(x){PORTA_OUT|=BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU|=BIT(8);PORTA_PD&=~BIT(8);}else{PORTA_OUT&=~BIT(8);PORTA_DIR&=~BIT(8);PORTA_PU&=~BIT(8);PORTA_PD|=BIT(8);}
#define LED_SET_PIN5(x) if(x){PORTA_OUT|=BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU|=BIT(9);PORTA_PD&=~BIT(9);}else{PORTA_OUT&=~BIT(9);PORTA_DIR&=~BIT(9);PORTA_PU&=~BIT(9);PORTA_PD|=BIT(9);}
#define LED_SET_PIN6(x) if(x){PORTA_OUT|=BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU|=BIT(10);PORTA_PD&=~BIT(10);}else{PORTA_OUT&=~BIT(10);PORTA_DIR&=~BIT(10);PORTA_PU&=~BIT(10);PORTA_PD|=BIT(10);}
#define LED_SET_PIN7(x) if(x){PORTA_OUT|=BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU|=BIT(11);PORTA_PD&=~BIT(11);}else{PORTA_OUT&=~BIT(11);PORTA_DIR&=~BIT(11);PORTA_PU&=~BIT(11);PORTA_PD|=BIT(11);}
#endif
#elif defined(SUPPORT_LCD_4COM_9SEG_MODE)
#ifdef LCD_USE_COMpb6789_GRIDpa151411_6_4
#define BK_LIGHT(x) if(x){PORTB_OUT|=BIT(10);PORTB_DIR&=~BIT(10);PORTB_PU|=BIT(10);PORTB_PD&=~BIT(10);}else{PORTB_OUT&=~BIT(10);PORTB_DIR&=~BIT(10);PORTB_PU&=~BIT(10);PORTB_PD|=BIT(10);}
#if 0
#define LCD_INIT()/*[5:4]:OSC*/ CLK_CON1 &= ~(BIT(5)|BIT(4));\
     /*[6:4]:VLCDS 3.0V*/     LCDC_CON0 = (0x0007<<4);\
     /*[11:8]½»Ìæ³äµçÄ£Ê½ÏÂÉèÖÃ*/ LCDC_CON0|=(0x0003<<8);\
     /*//[7]:32KHZ/64*/        LCDC_CON0 &=~ BIT(7);\
     /*//[13:12]:CHGMOD */ LCDC_CON0 |= (0x0002<<12);\
     /*[3:2]:0x01:1/2 BiasÂ¡Â£0x02:1/3Â¡Â£0x03:1/4*/                  LCDC_CON0 |= (0x0002<<2);\
     /*//[15:14] 01 com0-com3*/                  LCDC_CON0 |= (0x0001<<14);\ 
     /*[1]DOTEN*/                              LCDC_CON0 |= BIT(1);\                                   
     /*//[0] LCDCEN ÃŠÂ¹Ã„ÃœÃ•Ã¢Â¸Ã¶Ã„Â£Â¿Ã©*/                  LCDC_CON0 |= 0x01;\
     /*//PA4PA6-PA11Â£Â¬PA14-PA15*/                  SEG_IOEN0 = 0xCFD0;\
     /*background light on*/                      BK_LIGHT(1)
#else
#define LCD_INIT()/*[5:4]:OSC*/ CLK_CON1 &= ~(BIT(5)|BIT(4));\
     /*[6:4]:VLCDS 3.0V*/     LCDC_CON0 = 0x0007<<4;\
     /*//[7]:32KHZ/64*/        LCDC_CON0 |= BIT(7);\
     /*//[13:12]:CHGMOD Ã’Â»Ã–Â±Ã‡Â¿Â³Ã¤ÂµÃ§*/ LCDC_CON0 |= 0x0001<<12;\
     /*[3:2]:0x01:1/2 BiasÂ¡Â£0x02:1/3Â¡Â£0x03:1/4*/                  LCDC_CON0 |= 0x0002<<2;\
     /*//[15:14] 01 com0-com3*/                  LCDC_CON0 |= 0x0001<<14;\ 
     /*//[0] LCDCEN ÃŠÂ¹Ã„ÃœÃ•Ã¢Â¸Ã¶Ã„Â£Â¿Ã©*/                  LCDC_CON0 |= 0x01;\
     /*//PA4PA6-PA11Â£Â¬PA14-PA15*/                  SEG_IOEN0 = 0xCFD0;\
     /*background light on*/                      BK_LIGHT(1)
#endif     
#define LCD_SEG_CLOSE()  BK_LIGHT(0);\
                       LCDC_CON0=0;\
                       SEG_IOEN0=0
                       
#ifdef LCD_COM_REVERSE
#define COM0_SEG(x)	{PORTA_DIE &= ~0xCFD0;  PORTA_DIE |=(x&0xCFD0);}
#define COM1_SEG(x)	{PORTA_HD &= ~0xCFD0;  PORTA_HD |=(x&0xCFD0);}
#define COM2_SEG(x)	{PORTA_PD &= ~0xCFD0;  PORTA_PD |=(x&0xCFD0);}
#define COM3_SEG(x)	{PORTA_PU &= ~0xCFD0;  PORTA_PU |=(x&0xCFD0);}
#define LCD_SEG_CLEAR() {COM0_SEG(0x0000);COM1_SEG(0x0000);COM2_SEG(0x0000);COM3_SEG(0x0000);}                                               
#else
#define COM3_SEG(x)	{PORTA_DIE &= ~0xCFD0;  PORTA_DIE |=(x&0xCFD0);}
#define COM2_SEG(x)	{PORTA_HD &= ~0xCFD0;  PORTA_HD |=(x&0xCFD0);}
#define COM1_SEG(x)	{PORTA_PD &= ~0xCFD0;  PORTA_PD |=(x&0xCFD0);}
#define COM0_SEG(x)	{PORTA_PU &= ~0xCFD0;  PORTA_PU |=(x&0xCFD0);}
#define LCD_SEG_CLEAR() {COM0_SEG(0x0000);COM1_SEG(0x0000);COM2_SEG(0x0000);COM3_SEG(0x0000);}                                               
#endif
#endif
#elif defined(SUPPORT_LCD_5COM_8SEG_MODE)
#ifdef LCD_USE_COMpb10_pb6_GRIDpa6_pa15
 #define BK_LIGHT(x) ; //if(x){PORTB_OUT|=BIT(10);PORTB_DIR&=~BIT(10);PORTB_PU|=BIT(10);PORTB_PD&=~BIT(10);}else{PORTB_OUT&=~BIT(10);PORTB_DIR&=~BIT(10);PORTB_PU&=~BIT(10);PORTB_PD|=BIT(10);}
#define LCD_INIT()/*[5:4]:OSC*/ CLK_CON1 &= ~(BIT(5)|BIT(4));\
     /*[6:4]:VLCDS 3.0V*/     LCDC_CON0 = 0x0007<<4;\
     /*//[7]:32KHZ/64*/        LCDC_CON0 |= BIT(7);\
     /*//[13:12]:CHGMOD Ã’Â»Ã–Â±Ã‡Â¿Â³Ã¤ÂµÃ§*/ LCDC_CON0 |= 0x0001<<12;\
     /*[3:2]:0x01:1/2 BiasÂ¡Â£0x02:1/3Â¡Â£0x03:1/4*/                  LCDC_CON0 |= 0x0002<<2;\
     /*//[15:14] 01 com0-com3*/                  LCDC_CON0 |= 0x0002<<14;\ 
     /*//[0] LCDCEN ÃŠÂ¹Ã„ÃœÃ•Ã¢Â¸Ã¶Ã„Â£Â¿Ã©*/                  LCDC_CON0 |= 0x01;\
     /*//PA4PA6-PA11Â£Â¬PA14-PA15*/                  SEG_IOEN0 = 0xCFC0;\

//	1100 1111 1100 0000
     
     /*background light on*/                      BK_LIGHT(1)
#define LCD_SEG_CLOSE()  BK_LIGHT(0);\
						   LCDC_CON0=0;\
						   SEG_IOEN0=0
						   
#define COM4_SEG(x)	{PORTA_DIE &= ~0xCFC0;  PORTA_DIE |=(x&0xCFC0);}
#define COM3_SEG(x)	{PORTA_HD &= ~0xCFC0;  PORTA_HD |=(x&0xCFC0);}
#define COM2_SEG(x)	{PORTA_PD &= ~0xCFC0;  PORTA_PD |=(x&0xCFC0);}
#define COM1_SEG(x)	{PORTA_PU &= ~0xCFC0;  PORTA_PU |=(x&0xCFC0);}
#define COM0_SEG(x)	{PORTA_OUT&= ~0xCFC0;  PORTA_OUT |=(x&0xCFC0);}

#define LCD_SEG_CLEAR() {COM0_SEG(0x0000);COM1_SEG(0x0000);COM2_SEG(0x0000);COM3_SEG(0x0000);COM4_SEG(0x0000);}                                               
#endif
#endif

#if defined(SUPPORT_LCD_4COM_9SEG_MODE)||defined(SUPPORT_LCD_5COM_8SEG_MODE)
typedef struct _led7_VAR
{
    u8  bCoordinateX;
    u8  bFlashChar;
    #if defined LCD_ID_JXH_S6002A ||defined LCD_ID_XS700038B
    u8 wFlashIcon;
    u8 wLedIcon;
    #else
    u16 wFlashIcon;
    u16 wLedIcon;
    #endif
    u8  bShowBuff[LED_8NUMS];
    u8  bBrightness;
    u16  bShowBuff1[LED_COM_MAX];
    #ifdef USE_HT1628_CONTROL_TENS_OF_RGB_LIGHTS
    u8 bShowData[6];
    u8 bLightDataBuf[6];
    #endif
   #ifdef SUPPORT_EQ_FREQUENCE
    u8 bEqIconBuf;
   #endif
    bool bBtIfConnect; //jude if bt connected
    u32 dwDeviceID;
    u32 blast_play_device;
    #ifdef SUPPORT_BAT_DETECT_USE_IO
    u16 wAdc_value;
    #endif
    
#ifdef POWER_ON_WELCOME_VOICE_PLAYED_IN_IDLE_MODE
   bool bIfPlayWelcomeVoice;
#endif
}LED7_VAR;
#else

typedef struct _led7_VAR
{
    u8  bCoordinateX;
    u8  bFlashChar;    
    u16 wFlashIcon;
    u16 wLedIcon;
    u8  bShowBuff[LED_8NUMS];
    u8  bBrightness;
    u8  bShowBuff1[LED_COM_MAX];
    #ifdef USE_HT1628_CONTROL_TENS_OF_RGB_LIGHTS
    u8 bShowData[6];
    u8 bLightDataBuf[6];
    #endif
    #ifdef LED_EQ_BAR_SHOW
    u8 bEqBarBuf[LED_EQ_NUMS];
    u16 bEqBarEnergyValueBuf[LED_EQ_NUMS];
    u8 bEqMode;
    bool bEqPlayFlag;
    #endif
 #ifdef SUPPORT_EQ_FREQUENCE
	 #ifdef LED_ID_SD40C18SRB		
	 	u16 bEqIconBuf;
	 #else
	 	u8 bEqIconBuf;
	 #endif
 #endif
    bool bBtIfConnect; //jude if bt connected    
    u32 dwDeviceID;    
    u32 blast_play_device;
    #ifdef SUPPORT_BAT_DETECT_USE_IO
    u16 wAdc_value;
    #endif    
#ifdef EQ_ADC_VALUE_DETECT   
  #if 0//LED_EQ_NUMS
    u16 wEqADC_Value[LED_EQ_NUMS];
  #else
   u8 wEqADC_Value;
  #endif
#endif
#if TEST_IR_EN
    u8 testIrCode;
    u16 testIrSysCode;
#endif
#if defined(LED_ID_JW2781)||defined(LED_ID_WLD007)
    u8 bCircleBuf;
#endif
    bool bEqCircleIfPlay;  //use for eq/eq bar/circle if show
    
#ifdef SUPPORT_TM1628_KEY_READ
    u16 wTm1628KeyData; //H8 BYTE L8 DATA
#endif

#ifdef LED_SHOW_BT_EQ
   u8 bBtEqMode;
#endif
#ifdef POWER_ON_WELCOME_VOICE_PLAYED_IN_IDLE_MODE
   bool bIfPlayWelcomeVoice;
#endif
#ifdef SUPPORT_VOICE_ONOFF
#if defined SUPPORT_ZY_SA_VOICE||defined support_voice_onoff_mem
u8 bIfHaveVoice;
#else
bool bIfHaveVoice;
#endif
#endif
}LED7_VAR;
#endif


//bool Sys_HalfSec;
extern 	LED7_VAR led7_var;
#endif //UI_ENABLE

#ifdef support_menu_mode
extern u8 menumode;
#endif
#ifdef LED_SCREEN_SHOW_BAT_STATUS
extern void led7_show_bat_status(void);
#endif


//void set_LED_fade_out(void);
//void set_LED_all_on(void);

void led7_init(void);
void led7_scan(void);
void led7_clear_icon(void);
void led7_show_char(u8 chardata);
void led7_show_number(u8 number);
void led7_show_Hi(void);
void led7_show_music_main(void);
void led7_show_RTC_main(void);
void led7_show_filenumber(void);
void led7_show_volume(void);
void led7_show_fm_main(void);
void led7_show_IR_number(void);
void led7_show_pc_main(void);
void led7_show_pc_vol_up(void);
void led7_show_pc_vol_down(void);
void led7_show_aux_main(void);
void led7_show_eq(void);
//void led7_show_ef(void);
//void led7_show_speed(void);
//void led7_show_pitch(void);
void led7_show_playmode(void);
void led7_show_pause(void);
void led7_show_fm_station(void);
void led7_show_waiting(void);
void led7_show_alarm(void);
void led7_show_nop(void);
//void led7_show_echo(void);
void led7_show_rec_start(void);
void led7_show_rec_main(void);
void led7_clear(void);
#ifdef SUPPORT_MUSIC_STOP
void led7_show_stop(void);
#endif
#ifdef LED_SHOW_DEVICE_PLUGIN
void led7_show_plugin_dev(void);
#endif
#ifdef LED_EQ_BAR_SHOW
void LED_SHOW_EQ_BAR(u8 barNum,int mode,u8 steps);
void LED_EQ_BAR_PROCESS(u8 mode);
#endif
#ifdef SUPPORT_EQ_FREQUENCE
void LED_FREQUENCE_PROCESS(void);
#endif
#ifdef support_aux_energy_det
void	aux_auto_mute(void);
#endif

#ifdef SUPPORT_TM1628_KEY_READ
tu8 get_led_driver_key_value(void);
#endif

#ifdef LED_SHOW_ONOFF
void LED7_SHOW_LED_ONOFF(void);
#endif

#define LED_STATUS  led7_var.wLedIcon
#define LED_FLASH_ICON led7_var.wFlashIcon
#define LED_FLASH_CHAR led7_var.bFlashChar

#define LED_A   BIT(0)
#define LED_B	BIT(1)
#define LED_C	BIT(2)
#define LED_D	BIT(3)
#define LED_E	BIT(4)
#define LED_F	BIT(5)
#define LED_G	BIT(6)
#define LED_H	BIT(7)

#ifdef SUPPORT_EQ_FREQUENCE
 #ifdef LED_ID_SD40C18SRB		
#define EQ_00  0x01
#define EQ_01  0x02
#define EQ_02  0x04
#define EQ_03  0x08
#define EQ_04  0x10
#define EQ_05  0x20
#define EQ_06  0x40
#define EQ_07  0x80
#define EQ_08  0x100
#define EQ_09  0x200
#else
#define EQ_00  0x01
#define EQ_01  0x02
#define EQ_02  0x04
#define EQ_03  0x08
#define EQ_04  0x10
#define EQ_05  0x20
#define EQ_06  0x40
#define EQ_07  0x80
#endif
#endif

#ifdef LED_ID_KF8845AB
#define LED_BT 0x01
#define LED_USB 0x02
#define LED_SD 0x04
#define LED_RECO 0x08
#define LED_2POINT 0x10
#define LED_DOT 0x20
#define LED_REPLAY 0x40
#define LED_BAT01 0x80
#define LED_BAT02 0x0100
#define LED_BAT03 0x0200

#define LED_MHZ	    0
#define LED_MP3     0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_FM      0
#elif defined(LED_ID_8848)
#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_USB     0x04
#define LED_SD      0x08
#define LED_FM	    0x10
#define LED_MP3     0x20
#define LED_DOT     0x40
#define LED_2POINT  0x80

#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_BT 0
#define LED_MHZ	    0
#define LED_RECO 0
#define LED_2POINT1 0

#elif defined(LED_ID_8848_BAT)
#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_USB     0x04
#define LED_SD      0x08
#ifdef SUPPORT_BAT_DETECT
#define LED_BAT_FULL	0x10
#define LED_BAT_HALF	0x20
#else
#define LED_BAT_FULL	0
#define LED_BAT_HALF	0
#endif
#define LED_DOT     0x40
#define LED_2POINT  0x80

#define LED_FM	    0
#define LED_MP3     0

#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_BT 0
#define LED_MHZ	    0
#define LED_RECO 0
#define LED_2POINT1 0
#elif defined(LED_ID_JW_24017_1B)
#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_USB     0x04
#define LED_SD      0x08
#define LED_BAT_FULL	0x10
#define LED_BAT_HALF	0x20
#define LED_DOT     0x40
#define LED_2POINT  0x80

#define LED_FM	    0
#define LED_MP3     0

#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_BT 0
#define LED_MHZ	    0
#define LED_RECO 0
#define LED_2POINT1 0
#elif defined(LED_ID_8812N)
//LED_AUX,LED_BAT_FULL,LED_BAT_HALF,  LED_USB, LED_CARD,  LED_FM,LED_2POINT
  #define LED_AUX     0x01
  #define LED_BAT_FULL 0x02
  #define LED_BAT_HALF 0x04
  #define LED_USB     0x08
  #define LED_SD      0x10
  #define LED_FM	    0x20
  #define LED_2POINT  0x40
  
  #define LED_MP3 	0
  #define LED_DOT 	0
  #define LED_REPLAY 0
  #define LED_BAT01 0
  #define LED_BAT02 0
  #define LED_BAT03 0
  #define LED_BT 0
  #define LED_MHZ	    0
  #define LED_PLAY  0
  #define LED_PAUSE 0
#elif defined(LED_ID_8812)
//LED_AUX,LED_BAT_FULL,LED_BAT_HALF,  LED_USB, LED_CARD,  LED_FM,LED_2POINT
  #define LED_AUX     0x01
  #define LED_BAT_FULL 0x02
  #define LED_BAT_HALF 0x04
  #define LED_USB     0x08
  #define LED_SD      0x10
  #define LED_FM	    0x20
  #define LED_2POINT  0x40
  
  #define LED_MP3 	0
  #define LED_DOT 	0
  #define LED_REPLAY 0
  #define LED_BAT01 0
  #define LED_BAT02 0
  #define LED_BAT03 0
  #define LED_BT 0
  #define LED_MHZ	    0
  #define LED_PLAY  0
  #define LED_PAUSE 0
#elif defined(LED_ID_TY_8848)||defined(LED_ID_XTX2401_KB)||defined(LED_ID_XS700037A11)
#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_USB     0x04
#define LED_SD      0x08
#define LED_FM	    0x10
#define LED_MP3     0x20
#define LED_2POINT  0x40

#define LED_DOT     0
#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_BT 0
#define LED_MHZ	    0
#define LED_RECO	    0
#elif defined(LED_ID_SDX_88T48)

#ifdef LED_88T48_AZS_ICON

#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_USB     0x04
#define LED_SD      0x08
#define LED_BT	    0
#define LED_FM     0x10
#define LED_2POINT  0x40
#define LED_DOT     0x80
#define LED_2POINT1  0
#define LED_RECO  0
#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_MP3    0x20
#define LED_MHZ	   0 
#else
#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_USB     0x04
#define LED_SD      0x08
#define LED_BT	    0x10
#define LED_FM     0x20
#define LED_2POINT  0x40
#define LED_DOT     0x80
#define LED_2POINT1  0
#define LED_RECO  0
#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_MP3    0
#define LED_MHZ	    0
#endif

#elif defined(LED_ID_4018N_2B)
	//LED_AUX,LED_SD,LED_USB,LED_FM,LED_2POINT,LED_DOT,LED_BAT
#define LED_AUX     0X01	
#define LED_SD      0x02
#define LED_USB     0x04
#define LED_FM	    0x08
#define LED_2POINT  0x10
#define LED_DOT     0X20
#define LED_BAT    0X40

#define LED_MP3     0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_BT 0
#define LED_MHZ	    0
#define LED_2POINT1 0
#define LED_RECO    0
#elif defined(LED_ID_4018N_2)
#ifdef SUPPORT_OFF_USB_SD_ICON
#define LED_USB     0x00
#define LED_SD      0x00
#else
#define LED_USB     0x01
#define LED_SD      0x02
#endif
#define LED_FM	    0x04
#define LED_AUX     0X08
#define LED_2POINT  0x10
#define LED_DOT     0X20
#define LED_BAT    0X40

#define LED_MP3     0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_BT 0
#define LED_MHZ	    0
#define LED_2POINT1 0
#define LED_RECO    0
#elif defined(LED_ID_40N18SRB_15)
//LED_BT_MUSIC,LED_SD,LED_USB,LED_RECO,LED_2POINT,LED_DOT,LED_REPLAY
#define LED_BT_MUSIC 0x01
#define LED_SD      0x02
#define LED_USB     0x04
#define LED_RECO    0x08
#define LED_2POINT  0x10
#define LED_DOT     0X20
#define LED_REPLAY  0x40

#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_BT 0
#define LED_MHZ	    0
#define LED_FM	    0
#define LED_AUX     0
#define LED_BAT    0
#define LED_MP3     0
#define LED_2POINT1 0
#elif defined(LED_ID_JW4018D_3)
//LED_AUX,LED_USB,LED_SD,LED_FM,LED_MP3,LED_2POINT,LED_DOT,LED_BAT01,LED_BAT02,LED_BAT03
#define LED_AUX     0X01
#define LED_USB     0x02
#define LED_SD      0x04
#define LED_FM	    0x08
#define LED_MP3     0x10
#define LED_2POINT  0x20
#define LED_DOT     0x40
#define LED_BAT01   0x80
#define LED_BAT02   0x0100
#define LED_BAT03   0x0200

#define LED_PLAY	0
#define LED_RECO	0
#define LED_PAUSE	0
#define LED_REPLAY  0
#define LED_BT      0
#define LED_MHZ	    0
#define LED_BAT     0
#elif defined(LED_ID_JW4018D_1A)
//LED_PLAY,LED_USB,LED_PAUSE,LED_SD,LED_FM,LED_2POINT,LED_DOT,LED_BAT01,LED_BAT02,LED_BAT03
#define LED_PLAY	0x01
#define LED_USB     0x02
#define LED_PAUSE	0x04
#define LED_SD      0x08
#define LED_FM	    0x10
#define LED_2POINT  0x20
#define LED_DOT     0x40
#define LED_BAT01   0x80
#define LED_BAT02   0x0100
#define LED_BAT03   0x0200

#define LED_REPLAY  0
#define LED_BT      0
#define LED_MHZ	    0
#define LED_BAT     0
#define LED_AUX     0
#define LED_MP3     0

#elif defined LED_ID_40T18SRB
//LED_BT,LED_SD,LED_USB,LED_RECO,LED_REPLAY,LED_2POINT,LED_DOT,LED_BAT01,LED_BAT02,LED_BAT03
#define LED_BT      0x01
#define LED_SD      0x02
#define LED_USB     0x04
#define LED_RECO    0x08
#define LED_REPLAY  0x10
#define LED_2POINT  0x20
#define LED_DOT     0x40
#define LED_BAT01   0x80
#define LED_BAT02   0x0100
#define LED_BAT03   0x0200

#define LED_MHZ	    0
#define LED_BAT     0
#define LED_AUX     0
#define LED_MP3     0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_FM	    0
#define LED_2POINT1 0
#define LED_MIC_PRIORY 0
#elif defined LED_ID_4018_73
//LED_BT,LED_SD,LED_USB,LED_RECO,LED_REPLAY,LED_2POINT,LED_DOT,LED_BAT01,LED_BAT02,LED_BAT03
#define LED_BT      0x01
#define LED_SD      0x02
#define LED_USB     0x04
#define LED_RECO    0x08
#define LED_REPLAY  0x10
#define LED_2POINT  0x20
#define LED_DOT     0x40
#define LED_BAT01   0x80
#define LED_BAT02   0x0100
#define LED_BAT03   0x0200

#define LED_MHZ	    0
#define LED_BAT     0
#define LED_AUX     0
#define LED_MP3     0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_FM	    0
#define LED_2POINT1 0
#define LED_MIC_PRIORY 0


#elif defined(LED_ID_JW4018D_1B)||defined(LED_ID_4018_72)
//LED_BT,LED_SD,LED_USB,LED_RECO,LED_REPLAY,LED_2POINT,LED_DOT,LED_BAT01,LED_BAT02,LED_BAT03
#define LED_BT      0x01
#define LED_SD      0x02
#define LED_USB     0x04
#define LED_RECO    0x08
#ifdef SUPPORT_REPEAT_ICON_OFF
#define LED_REPLAY  0
#else
#define LED_REPLAY  0x10
#endif
#define LED_2POINT  0x20
#define LED_DOT     0x40
#define LED_BAT01   0x80
#define LED_BAT02   0x0100
#define LED_BAT03   0x0200

#define LED_MHZ	    0
#define LED_BAT     0
#define LED_AUX     0
#define LED_MP3     0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_FM	    0
#define LED_2POINT1 0
#define LED_MIC_PRIORY 0
#elif defined(LCD_ID_JXH_S6002A)||defined(LCD_ID_HL_21716HNT)||defined(LCD_ID_ZSLCD)
#define LED_2POINT  0x01 //p1
#define LED_SD      0x02 //s1
#define LED_USB     0x04 //s2
#define LED_DOT     0x08 //s7

#define LED_BT      0x10 //s6
#define LED_RECO    0x20 //s5
#define LED_MUTE    0x40 //s4
#define LED_FOLDER  0x80 //s3

#define LED_REPLAY  0
#define LED_MHZ	    0
#define LED_BAT     0
#define LED_AUX     0
#define LED_MP3     0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_FM	    0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0

#elif defined(LCD_ID_XS700038B)
#define LED_BT      0x01 
#define LED_SD      0x02 
#define LED_USB     0x04
#define LED_2POINT  0x08 
#define LED_DOT     0x10
#define LED_RECO	0x20
#define LED_REPLAY  0x40

#define LED_MUTE    0 //s4
#define LED_2POINT1	    0
#define LED_FM	    0
#define LED_MHZ	    0
#define LED_BAT     0
#define LED_AUX     0
#define LED_MP3     0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_FOLDER  0 
#elif defined(LCD_ID_XH600002A)
#define LED_2POINT  0x01 //p1
#define LED_SD      0x02 //s1
#define LED_USB     0x04 //s2
#define LED_DOT     0x08 //s7
#define LED_REPLAY  0x10
#define LED_MUTE    0x20 //s4

#define LED_FM	    0
#define LED_MHZ	    0
#define LED_BAT     0
#define LED_AUX     0
#define LED_MP3     0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_BT      0 
#define LED_RECO    0 
#define LED_FOLDER  0 
#elif defined(LED_ID_KF8426GH)||defined(LED_ID_ZY3053)
//LED_PLAY,LED_PAUSE,LED_USB,LED_SD,LED_2POINT,LED_DOT,LED_MP3,LED_AUX,LED_BT,LED_MHZ
#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_USB      0x04
#define LED_SD     0x08
#define LED_2POINT  0x10
#define LED_DOT     0x20
#define LED_MP3     0x40
#define LED_AUX     0x80
#ifdef LED_NO_BT_ICON
#define LED_FM      0x0100
#else
#define LED_BT      0x0100
#endif
#define LED_MHZ	    0x0200

#define LED_REPEAT_ALL 0
#define LED_REPLAY  0
#define LED_DVD     0
#define LED_BAT     0
#ifdef LED_NO_BT_ICON
#define LED_BT      0
#else
#define LED_FM	    0
#endif
#define LED_RECO    0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_2POINT1 0
#elif defined(VFD_ID_YDL2001_35)
//LED_MP3,LED_ALL,LED_REPEAT,LED_PLAY,LED_PAUSE,LED_2POINT,LED_H2POINT,LED_C01,LED_C02,LED_C03
#define LED_MP3     0x01
#define LED_REPEAT_ALL 0x02
#define LED_REPEAT_ONE 0x04
#define LED_PLAY	0x08
#define LED_PAUSE	0x10
#define LED_2POINT  0x20
#define LED_2POINT1 0x40
#define LED_CIRCLE_01 0x80
#define LED_CIRCLE_02 0x0100
#define LED_CIRCLE_03 0x0200

#define LED_REPLAY  0
#define LED_DVD     0
#define LED_BAT     0
#define LED_FM	    0
#define LED_RECO    0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_USB      0
#define LED_SD     0
#define LED_DOT     0
#define LED_AUX     0
#define LED_BT      0
#define LED_MHZ	    0
#elif defined(LED_ID_JW8222_1B) //ÃŒÃ¬Â·Ã¥
//LED_SWVOL,LED_TRE,LED_DVD,LED_MP3,LED_2POINT,LED_DOT,LED_FM,LED_BT,LED_VOLUME,LED_SUBWOOFER
#define LED_SWVOL   0x01
#define LED_TRE     0x02
#define LED_DVD     0x04
#define LED_MP3     0x08
#define LED_2POINT  0x10
#define LED_DOT     0x20
#define LED_FM	    0x40
#define LED_BT      0x80
#define LED_VOLUME  0x0100
#define LED_SUBWOOFER 0x0200

#define LED_CIRCLE_01 0
#define LED_CIRCLE_02 0
#define LED_CIRCLE_03 0
#define LED_REPLAY  0
#define LED_BAT     0
#define LED_RECO    0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_USB      0
#define LED_SD     0
#define LED_AUX     0
#define LED_MHZ	    0
#define LED_REPEAT_ALL 0
#define LED_REPEAT_ONE 0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_2POINT1 0
#elif defined(LED_ID_YUNKE01)
//LED_SD,LED_USB,LED_DVD,LED_FM,LED_2POINT,LED_DOT,LED_AUX,LED_BT,LED_SUBWOOFER
#define LED_SD      0x01
#define LED_USB     0x02
#define LED_DVD     0x04
#define LED_FM	    0x08
#define LED_2POINT  0x10
#define LED_DOT     0x20
#define LED_AUX     0x40
#define LED_BT      0x80
#define LED_SUBWOOFER 0x0100

#define LED_CIRCLE_01 0
#define LED_CIRCLE_02 0
#define LED_CIRCLE_03 0
#define LED_REPLAY  0
#define LED_BAT     0
#define LED_RECO    0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_MHZ	    0
#define LED_REPEAT_ALL 0
#define LED_REPEAT_ONE 0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_2POINT1 0
#define LED_SWVOL   0
#define LED_TRE     0
#define LED_MP3     0
#define LED_VOLUME  0
#elif defined(LED_ID_JW5348_1A)
//LED_MP3,LED_DVD,LED_FM,LED_VOLUME,LED_2POINT,LED_DOT,LED_BT,LED_MHZ,LED_POWER
#define LED_MP3     0x01
#define LED_DVD     0x02
#define LED_FM	    0x04
#define LED_VOLUME  0x08
#define LED_2POINT  0x10
#define LED_DOT     0x20
#define LED_BT      0x40
#define LED_MHZ	    0x80
#define LED_POWER   0x0100

#define LED_SUBWOOFER 0
#define LED_CIRCLE_01 0
#define LED_CIRCLE_02 0
#define LED_CIRCLE_03 0
#define LED_REPLAY  0
#define LED_BAT     0
#define LED_RECO    0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_REPEAT_ALL 0
#define LED_REPEAT_ONE 0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_2POINT1 0
#define LED_SWVOL   0
#define LED_TRE     0
#define LED_SD      0
#define LED_USB     0
#define LED_AUX     0


#elif defined(LED_ID_DOUBLE_PANEL)
   //LED_1PONIT,LED_2PONIT,  LED_FM, 
   
  #define LED_USB     0
  #define LED_SD		0
  #define LED_MP3 	0
  #define LED_FM	    0x04
  #define LED_PLAY  0
  #define LED_PAUSE 0
  #define LED_2POINT  0x02  
  #define LED_REPEAT_ONE 0
  #define LED_2POINT2	0x01  
  #define LED_2POINT1	0  


  #define LED_DOT     0
  #define LED_AUX     0
  #define LED_BT      0
  #define LED_SUBWOOFER 0
  #define LED_CIRCLE_01 0
  #define LED_CIRCLE_02 0
  #define LED_CIRCLE_03 0
  #define LED_REPLAY  0
  #define LED_BAT     0
  #define LED_RECO    0
  #define LED_BAT01   0
  #define LED_BAT02   0
  #define LED_BAT03   0
  #define LED_MHZ	    0
  #define LED_REPEAT_ALL 0
  #define LED_SWVOL   0
  #define LED_TRE     0
  #define LED_VOLUME  0
  #define LED_DVD 	0
#elif defined(LED_ID_WLD007)
//LED_USB,LED_SD,LED_MP3,  LED_FM, LED_PLAY,  LED_PAUSE,LED_2POINT,LED_REPEAT
  #define LED_USB     0x01
  #define LED_SD		0x02
  #define LED_MP3 	0x04
  #define LED_FM	    0x08
  #define LED_PLAY  0x10
  #define LED_PAUSE 0x20
  #define LED_2POINT  0x40  
  #define LED_REPEAT_ONE 0x80
  #define LED_2POINT1	0x0100  


  #define LED_DOT     0
  #define LED_AUX     0
  #define LED_BT      0
  #define LED_SUBWOOFER 0
  #define LED_CIRCLE_01 0
  #define LED_CIRCLE_02 0
  #define LED_CIRCLE_03 0
  #define LED_REPLAY  0
  #define LED_BAT     0
  #define LED_RECO    0
  #define LED_BAT01   0
  #define LED_BAT02   0
  #define LED_BAT03   0
  #define LED_MHZ	    0
  #define LED_REPEAT_ALL 0
  #define LED_SWVOL   0
  #define LED_TRE     0
  #define LED_VOLUME  0
  #define LED_DVD 	0
#elif defined(LED_ID_JW2781)
#ifdef LED_ID_XL2781_2BYRG
//LED_USB,LED_BT,LED_AUX,  LED_FM, LED_PLAY,  LED_PAUSE,LED_2POINT,LED_REPEAT
  #define LED_USB     0x01
  #define LED_BT		0x02
  #define LED_AUX 	0x04
  #define LED_FM	    0x08
  #define LED_PLAY  0x10
  #define LED_PAUSE 0x20
  #define LED_2POINT  0x40  
  #define LED_REPEAT_ONE 0x80
  #define LED_EN_LED  0x100
  
  #define LED_SD		0
  #define LED_MP3 	0
  #define LED_DOT     0
  #define LED_SUBWOOFER 0
  #define LED_CIRCLE_01 0
  #define LED_CIRCLE_02 0
  #define LED_CIRCLE_03 0
  #define LED_REPLAY  0
  #define LED_BAT     0
  #define LED_RECO    0
  #define LED_BAT01   0
  #define LED_BAT02   0
  #define LED_BAT03   0
  #define LED_MHZ	    0
  #define LED_2POINT1 0
  #define LED_REPEAT_ALL 0
  #define LED_SWVOL   0
  #define LED_TRE     0
  #define LED_VOLUME  0
  #define LED_DVD 	0
#elif defined LED_ID_JW2781_J_HD03_A
//usb play  888:88:88 repeat
/* bt pause              	    */
/* aux fm    	         mhz  */

//LED_USB,LED_BT,LED_AUX,  LED_FM, LED_PLAY,  LED_PAUSE,LED_2POINT,LED_REPEAT,LED_MHZ

#define LED_USB     0x01
  #define LED_BT		0x02
  #define LED_AUX 	0x04
  #define LED_FM	    0x08
  #define LED_PLAY  0x10
  #define LED_PAUSE 0x20
  #define LED_2POINT  0x40  
  #define LED_REPEAT_ONE 0x80
  #define LED_EN_LED  0x100

  #define LED_MHZ	    0
  #define LED_DOT     0
  #define LED_MP3     0
  #define LED_SD      0
  #define LED_SUBWOOFER 0
  #define LED_CIRCLE_01 0
  #define LED_CIRCLE_02 0
  #define LED_CIRCLE_03 0
  #define LED_REPLAY  0
  #define LED_BAT     0
  #define LED_RECO    0
  #define LED_BAT01   0
  #define LED_BAT02   0
  #define LED_BAT03   0
  #define LED_2POINT1 0
  #define LED_REPEAT_ALL 0
  #define LED_SWVOL   0
  #define LED_TRE     0
  #define LED_VOLUME  0
  #define LED_DVD 	0
#else
//LED_USB,LED_SD,LED_MP3,  LED_FM, LED_PLAY,  LED_PAUSE,LED_2POINT,LED_REPEAT

#ifdef SUPPORT_OFF_USB_SD_ICON
  #define LED_USB     0
  #define LED_SD		0
#else
  #define LED_USB     0x01
  #define LED_SD		0x02
#endif

  #define LED_MP3 	0x04
  #define LED_FM	    0x08
  #define LED_PLAY  0x10
  #define LED_PAUSE 0x20
  #define LED_2POINT  0x40  
  #define LED_REPEAT_ONE 0x80

  #define LED_DOT     0
  #define LED_AUX     0
  #define LED_BT      0
  #define LED_SUBWOOFER 0
  #define LED_CIRCLE_01 0
  #define LED_CIRCLE_02 0
  #define LED_CIRCLE_03 0
  #define LED_REPLAY  0
  #define LED_BAT     0
  #define LED_RECO    0
  #define LED_BAT01   0
  #define LED_BAT02   0
  #define LED_BAT03   0
  #define LED_MHZ	    0
  #define LED_2POINT1 0
  #define LED_REPEAT_ALL 0
  #define LED_SWVOL   0
  #define LED_TRE     0
  #define LED_VOLUME  0
  #define LED_DVD 	0
#endif  
#elif defined(LED_ID_KF33T1) //ÃŒÃ¬Â·Ã¥
//LED_USB,LED_SD,LED_REPEAT,LED_FM,LED_2POINT,LED_DOT,LED_BAT01,LED_BAT02,LED_BAT03,LED_BAT04,LED_BAT_FRAME
#define LED_USB      0x01
#define LED_SD     0x02
#define LED_REPEAT_ONE 0x04
#define LED_FM	    0x08
#define LED_2POINT  0x10
#define LED_DOT     0x20
#define LED_BAT01   0x40
#define LED_BAT02   0x80
#define LED_BAT03   0x0100
#define LED_BAT04   0x0200
#define LED_BAT_FRAME   0x0400

#define LED_CIRCLE_01 0
#define LED_CIRCLE_02 0
#define LED_CIRCLE_03 0
#define LED_REPLAY  0
#define LED_BAT     0
#define LED_RECO    0
#define LED_AUX     0
#define LED_MHZ	    0
#define LED_REPEAT_ALL 0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_2POINT1 0
#define LED_SWVOL   0
#define LED_TRE     0
#define LED_DVD     0
#define LED_MP3     0
#define LED_BT      0
#define LED_VOLUME  0
#define LED_SUBWOOFER 0
#elif defined(LED_ID_KD048AR_P15)
// LED_TF,	 LED_FM,  LED_REC, LED_REPEAT, LED_BAT_FULL,  LED_BAT_HALF,LED_DOT,LED_2POINT
#define LED_SD      0x01
#define LED_MIC_PRIORY	    0x02
#define LED_RECO 0x04
#define LED_REPEAT_ONE 0x08
#define LED_BAT_FULL 0x10
#define LED_BAT_HALF 0x20
#define LED_DOT     0x40
#define LED_2POINT  0x80

#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_BT 0
#define LED_MHZ	    0
#define LED_2POINT1 0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_MP3     0
#define LED_FM     0
#define LED_REPEAT_ALL 0
#define LED_USB      0
#elif defined(LED_ID_SD28N20)
// LED_TF,	 LED_USB,  LED_REC, LED_REPEAT, LED_MIC,LED_BAT_FULL,  LED_BAT_HALF,LED_DOT,LED_2POINT
#define LED_SD      0x01
#define LED_USB      0x02
#define LED_RECO 0x04
#define LED_REPEAT_ONE 0x08
#define LED_MIC_PRIORY	    0x10
#define LED_BAT_FULL 0x20
#define LED_BAT_HALF 0x40
#define LED_DOT     0x80
#define LED_2POINT  0x0100

#define LED_REPLAY 0
#define LED_BAT01 0
#define LED_BAT02 0
#define LED_BAT03 0
#define LED_BT 0
#define LED_MHZ	    0
#define LED_2POINT1 0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_MP3     0
#define LED_FM     0
#define LED_REPEAT_ALL 0

#elif defined(LED_ID_JM_950)


#define LED_DOT     0x01
#define LED_CD     0x02
#define LED_DVD     0x04
#define LED_VOL     0x08
#define LED_FR    0x10
#define LED_SUR     0x20
#define LED_CEN     0x40
#define LED_SWVOL     0x80
#define LED_MIC	     0x100
#define LED_DECHO     0x200
#define LED_USB     0x400
#define LED_FM     0x800


#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_2POINT  0
#define LED_2POINT1 0
#define LED_MP3     0
#define LED_SRS     0

#define LED_SD     0
#define LED_REPEAT_ONE 0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_BAT04   0
#define LED_BAT_FRAME   0
#define LED_CIRCLE_01 0
#define LED_CIRCLE_02 0
#define LED_CIRCLE_03 0
#define LED_REPLAY  0
#define LED_BAT     0
#define LED_RECO    0
#define LED_AUX     0
#define LED_MHZ	    0
#define LED_REPEAT_ALL 0
#define LED_TRE     0
#define LED_BT      0
#define LED_VOLUME  0
#define LED_SUBWOOFER 0

#elif defined(LED_ID_ZX001)||defined(LED_ID_JW1676_1B)||defined(LED_ID_JM_4169_B)
//LED_PLAY,LED_PAUSE,LED_2POINT,LED_2POINT1,LED_DOT,LED_MP3,LED_DVD,LED_SRS
#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_2POINT  0x04
#define LED_2POINT1 0x08
#define LED_DOT     0x10
#define LED_MP3     0x20
#define LED_DVD     0x40
#define LED_SRS     0x80

#define LED_USB      0
#define LED_SD     0
#define LED_REPEAT_ONE 0
#define LED_FM	    0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_BAT04   0
#define LED_BAT_FRAME   0
#define LED_CIRCLE_01 0
#define LED_CIRCLE_02 0
#define LED_CIRCLE_03 0
#define LED_REPLAY  0
#define LED_BAT     0
#define LED_RECO    0
#define LED_AUX     0
#define LED_MHZ	    0
#define LED_REPEAT_ALL 0
#define LED_SWVOL   0
#define LED_TRE     0
#define LED_BT      0
#define LED_VOLUME  0
#define LED_SUBWOOFER 0


#elif defined(LED_ID_JW8426C7_1B) ||defined(LED_ID_JW84267_4) 

/*
	PLAY				MP3
	PAUSE 	8:88:8.8      	AUX
	USB					FM
	SD					MHZ
*/

//LED_PLAY,LED_PAUSE,LED_USB,LED_SD,LED_2POINT,LED_DOT,LED_MP3,LED_AUX,LED_FM,LED_MHZ

#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_USB     0x04
#define LED_SD      0x08
#define LED_2POINT  0x10
#define LED_DOT     0x20
#define LED_MP3     0x40
#define LED_AUX     0x80
#define LED_FM	    0x0100
#define LED_MHZ	    0x0200

#define LED_RECO    0
#define LED_REPLAY  0
#define LED_2POINT1 0

#elif defined(LED_ID_JW4520_2A) //13pin led
//LED_PLAY,LED_PAUSE,LED_2POINT,LED_DOT,LED_MP3,LED_USB,LED_SD,LED_IPHONE,LED_AUX,LED_FM,LED_MHZ
#define LED_PLAY	0x01
#define LED_PAUSE	0x02
#define LED_2POINT  0x04
#define LED_DOT     0x08
#define LED_MP3     0x10
#define LED_USB     0x20
#define LED_SD      0x40
#define LED_IPHONE  0x80
#define LED_AUX     0x0100
#define LED_FM	    0x0200
#define LED_MHZ	    0x0400

#define LED_DVD     0
#define LED_SRS     0
#define LED_REPEAT_ONE 0
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#define LED_BAT04   0
#define LED_BAT_FRAME   0
#define LED_CIRCLE_01 0
#define LED_CIRCLE_02 0
#define LED_CIRCLE_03 0
#define LED_REPLAY  0
#define LED_BAT     0
#define LED_RECO    0
#define LED_REPEAT_ALL 0
#define LED_SWVOL   0
#define LED_TRE     0
#define LED_BT      0
#define LED_VOLUME  0
#define LED_SUBWOOFER 0
#define LED_2POINT1 0

 #elif defined LED_ID_SD40C18SRB
 
  //LED_BT,    LED_USB,   LED_SD,  LED_REC, LED_2POINT, LED_2POINT1,LED_DOT,LED_REPLAY,LED_BAT01,LED_BAT02,LED_BAT03
#define LED_BT      0X01
#define LED_USB     0x02
#define LED_SD      0x04
#define LED_RECO    0X08
#define LED_2POINT  0x10
#define LED_2POINT1 0X20
#define LED_DOT     0x40
#define LED_REPLAY  0X80
#if defined SUPPORT_OFF_BAT_ICON
#define LED_BAT01   0
#define LED_BAT02   0
#define LED_BAT03   0
#else
#define LED_BAT01   0X100
#define LED_BAT02   0X200
#define LED_BAT03   0X400
#endif

#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_MP3    	 0
#define LED_IPHONE  0
#define LED_AUX       0
#define LED_FM	      0
#define LED_MHZ	      0
#define LED_DVD     0
#define LED_SRS     0
#define LED_REPEAT_ONE 0
#define LED_BAT04   0
#define LED_BAT_FRAME   0
#define LED_CIRCLE_01 0
#define LED_CIRCLE_02 0
#define LED_CIRCLE_03 0
#define LED_BAT     0
#define LED_REPEAT_ALL 0
#define LED_SWVOL   0
#define LED_TRE     0
#define LED_VOLUME  0
#define LED_SUBWOOFER 0

#elif defined LED_ID_27N60_8

/*
	tf	   fm
|||| 88:8.8 ||||
	usb	  aux
*/

//LED_SD,LED_USB,LED_FM,LED_AUX,LED_2POINT,LED_DOT

       #define LED_SD		  LED_A
       #define LED_USB		LED_B
       #define LED_FM		LED_C
       #define LED_AUX		  LED_D
       #define LED_2POINT	  LED_E
	#define   LED_DOT         LED_F
       #define LED_MHZ	         0
       #define LED_PLAY	        0
       #define LED_PAUSE	0       
       #define LED_MP3		0

	   
#elif defined(LED_ID_JW54627_1BB) //ÃŒÃ¬Â·Ã¥
/*  8 8:8.8*/
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_USB		0
#define LED_SD		0
#define LED_2POINT	LED_A
#define LED_MHZ	    0
#define LED_DOT		LED_B
#define LED_MP3     0
 #define LED_RECO     0
  #define LED_FM     0
 #define LED_2POINT1	0
#elif defined(LED_ID_XS700037A11) //ÃŒÃ¬Â·Ã¥
/*  8 8:8.8*/
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_USB		0
#define LED_SD		0
#define LED_2POINT	LED_A
#define LED_MHZ	    0
#define LED_DOT		LED_B
#define LED_MP3     0
 #define LED_RECO     0
  #define LED_FM     0
 #define LED_2POINT1	0
#else
//for LED0
#define LED_PLAY	0
#define LED_PAUSE	0
#define LED_USB		0
#define LED_SD		0
#define LED_2POINT	0
#define LED_MHZ	    0
#define LED_DOT		0
#define LED_MP3     0
#endif


#ifdef SUPPORT_TM1628_KEY_READ

 #define LED_KEY_NEXT    0 
  #define LED_KEY_MUTE    1 
 #define LED_KEY_PP         2
 #define LED_KEY_MENU    3
 #define LED_KEY_PREV     4
 #define LED_KEY_MODE   5

#define LED_KEY_NULL 0xff
#endif



#endif	/*	_LED_H_	*/
