//generated by ResBuilder in 2014//
#ifndef _RES_H_  
#define _RES_H_  

////StringResID Define Table////
#define  Chinese_Simplified       1   //简体中文
#define  Chinese_Traditional      2   //繁体中文
#define  Japanese                 3   //日语
#define  Korean                   4   //韩语
#define  English                  5   //英语
#define  French                   6   //法语
#define  German                   7   //德语
#define  Italian                  8   //意大利语
#define  Dutch                    9   //荷兰语
#define  Portuguese               10  //葡萄牙语
#define  Spanish                  11  //西班牙语
#define  Swedish                  12  //瑞典语
#define  Czech                    13  //捷克语
#define  Danish                   14  //丹麦语
#define  Polish                   15  //波兰语
#define  Russian                  16  //俄语
#define  Turkey                   17  //土耳其语
#define  Hebrew                   18  //希伯来语
#define  Thai                     19  //泰语
#define  Hungarian                20  //匈牙利语
#define  Romanian                 21  //罗马尼亚语
#define  Arabic                   22  //阿拉伯语

#define  LANGUAGEID_SUM           22

////BmpResID Define Table////
#define  A0001JL                  1
#define  A0002JL                  2
#define  A0003JL                  3
#define  A0004JL                  4
#define  A0005JL                  5
#define  A0006JL                  6
#define  A0007JL                  7
#define  A0008JL                  8
#define  A0009JL                  9
#define  A0010JL                  10
#define  A0011JL                  11
#define  A0012JL                  12
#define  A0013JL                  13
#define  A0014JL                  14
#define  A0015JL                  15
#define  A0016JL                  16
#define  A0017JL                  17
#define  A0018JL                  18
#define  A0019JL                  19
#define  A0020JL                  20
#define  A0021JL                  21
#define  A0022JL                  22
#define  A0023JL                  23
#define  A0024JL                  24
#define  A0025JL                  25
#define  A0026JL                  26
#define  A0027JL                  27
#define  A0028JL                  28
#define  A0029JL                  29
#define  A0030JL                  30
#define  A0031JL                  31
#define  BT_LINK                  32
#define  BT_OFFSET                33
#define  BT_SERH                  34
#define  BT_TA2DP                 35
#define  BT_THFP                  36
#define  BT_THID                  37
#define  BT_TOSET                 38
#define  BT_WAIT                  39
#define  FOLDERM                  40
#define  PROGRESS                 41
#define  SLIDER_P                 42
#define  RESOLUTION               43  //分辨率
#define  MENU1                    44  //菜单1_菜单1_菜单1_菜单1_菜单1_菜单
#define  MENU2                    45  //菜单2
#define  MENU3                    46  //菜单3
#define  MENU                     47  //菜单
#define  MENU1_1                  48  //菜单1_1
#define  MENU1_2                  49  //菜单1_2

#endif
