

/*******************************************************************
                        IR music   按键表
*******************************************************************/
#define IRFF00_DECODE_KEY_SHORT			\
	/*00*/	  MSG_ONE_KEY_TO_BT,\
	/*01*/	  MSG_STANBY_KEY,\
	/*02*/	  MSG_ONE_KEY_TO_AUX,\
	/*03*/	  MSG_MUSIC_U_SD,\
	/*04*/	  MSG_ONE_KEY_TO_RADIO,\
	/*05*/	  MSG_FM_NEXT_STATION,\
	/*06*/	  MSG_FM_PREV_STATION,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  MSG_RESET_KEY,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  MSG_MUTE,\
	/*23*/	  MSG_MUSIC_PREV_FILE,\
	/*24*/	  MSG_MUSIC_NEXT_FILE,\
	/*25*/	  MSG_MUSIC_PP

#define IRFF00_DECODE_KEY_LONG			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  MSG_MUSIC_FR,\
	/*24*/	  MSG_MUSIC_FF,\
	/*25*/	  NO_MSG
#define IRFF00_DECODE_KEY_HOLD			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  MSG_MUSIC_FR,\
	/*24*/	  MSG_MUSIC_FF,\
	/*25*/	  NO_MSG

#define IRFF00_DECODE_KEY_LONG_UP 		\
	/*00*/     NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG

/*******************************************************************
                          FM   IR按键表
*******************************************************************/
#define IRFF00_FM_KEY_SHORT			\
	/*00*/	  MSG_ONE_KEY_TO_BT,\
	/*01*/	  MSG_STANBY_KEY,\
	/*02*/	  MSG_ONE_KEY_TO_AUX,\
	/*03*/	  MSG_ONE_KEY_TO_MP3,\
	/*04*/	  MSG_ONE_KEY_TO_RADIO,\
	/*05*/	  MSG_FM_NEXT_STATION,\
	/*06*/	  MSG_FM_PREV_STATION,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  MSG_RESET_KEY,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  MSG_MUTE,\
	/*23*/	  MSG_FM_PREV_STEP,\
	/*24*/	  MSG_FM_NEXT_STEP,\
	/*25*/	  MSG_FM_SCAN_ALL_INIT
#define IRFF00_FM_KEY_LONG			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  MSG_FM_SCAN_ALL_UP,\
	/*06*/	  MSG_FM_SCAN_ALL_DOWN,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  NO_MSG,\
	/*24*/	  NO_MSG,\
	/*25*/	  NO_MSG
#define IRFF00_FM_KEY_HOLD			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  NO_MSG,\
	/*24*/	  NO_MSG,\
	/*25*/	  NO_MSG

#define IRFF00_FM_KEY_LONG_UP 		\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG

/*******************************************************************
                     line        IR按键表
*******************************************************************/
#define IRFF00_AUX_KEY_SHORT			\
	/*00*/	  MSG_ONE_KEY_TO_BT,\
	/*01*/	  MSG_STANBY_KEY,\
	/*02*/	  MSG_ONE_KEY_TO_AUX,\
	/*03*/	  MSG_ONE_KEY_TO_MP3,\
	/*04*/	  MSG_ONE_KEY_TO_RADIO,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  MSG_RESET_KEY,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  MSG_MUTE,\
	/*23*/	  NO_MSG,\
	/*24*/	  NO_MSG,\
	/*25*/	  MSG_AUX_PAUSE
#define IRFF00_AUX_KEY_LONG			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  NO_MSG,\
	/*24*/	  NO_MSG,\
	/*25*/	  NO_MSG

#define IRFF00_AUX_KEY_HOLD			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  NO_MSG,\
	/*24*/	  NO_MSG,\
	/*25*/	  NO_MSG

#define IRFF00_AUX_KEY_LONG_UP 		\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG

/*******************************************************************
                        IR BT   按键表
*******************************************************************/
#define IRFF00_BT_SHORT			\
	/*00*/	  MSG_ONE_KEY_TO_BT,\
	/*01*/	  MSG_STANBY_KEY,\
	/*02*/	  MSG_ONE_KEY_TO_AUX,\
	/*03*/	  MSG_ONE_KEY_TO_MP3,\
	/*04*/	  MSG_ONE_KEY_TO_RADIO,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  MSG_RESET_KEY,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  MSG_MUTE,\
	/*23*/	  MSG_BT_PREV_FILE,\
	/*24*/	  MSG_BT_NEXT_FILE,\
	/*25*/	  MSG_BT_PP
#define IRFF00_BT_LONG			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  NO_MSG,\
	/*24*/	  NO_MSG,\
	/*25*/	  NO_MSG

#define IRFF00_BT_HOLD			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  NO_MSG,\
	/*24*/	  NO_MSG,\
	/*25*/	  NO_MSG


#define IRFF00_BT_LONG_UP 		\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG
/*******************************************************************
                      usb      IR按键表
*******************************************************************/
#define IRFF00_USB_KEY_SHORT			\
	/*00*/	  MSG_ONE_KEY_TO_BT,\
	/*01*/	  MSG_STANBY_KEY,\
	/*02*/	  MSG_ONE_KEY_TO_AUX,\
	/*03*/	  MSG_ONE_KEY_TO_MP3,\
	/*04*/	  MSG_ONE_KEY_TO_RADIO,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  MSG_RESET_KEY,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  MSG_MUTE,\
	/*23*/	  MSG_PC_PLAY_PREV,\
	/*24*/	  MSG_PC_PLAY_NEXT,\
	/*25*/	  MSG_PC_PP

#define IRFF00_USB_KEY_LONG			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  NO_MSG,\
	/*24*/	  NO_MSG,\
	/*25*/	  NO_MSG

#define IRFF00_USB_KEY_HOLD			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  MSG_MAIN_VOL_DN,\
	/*08*/	  MSG_MAIN_VOL_UP,\
	/*09*/	  NO_MSG,\
	/*10*/	  MSG_FRONT_LEFT_UP,\
	/*11*/	  MSG_FRONT_LEFT_DN,\
	/*12*/	  MSG_FRONT_RIGHT_UP,\
	/*13*/	  MSG_FRONT_RIGHT_DN,\
	/*14*/	  MSG_TREBLE_UP,\
	/*15*/	  MSG_TREBLE_DN,\
	/*16*/	  MSG_MIC_UP,\
	/*17*/	  MSG_MIC_DN,\
	/*18*/	  MSG_ECHO_UP,\
	/*19*/	  MSG_ECHO_DN,\
	/*20*/	  MSG_SWVOL_UP,\
	/*21*/	  MSG_SWVOL_DN,\
	/*22*/	  NO_MSG,\
	/*23*/	  NO_MSG,\
	/*24*/	  NO_MSG,\
	/*25*/	  NO_MSG

#define IRFF00_USB_KEY_LONG_UP 		\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG

/*******************************************************************
                     MAIN       IR按键表
*******************************************************************/
#define IRFF00_MAIN_KEY_SHORT			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG

#define IRFF00_MAIN_KEY_LONG			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG


#define IRFF00_MAIN_KEY_HOLD			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG

#define IRFF00_MAIN_KEY_LONG_UP 		\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG

/*******************************************************************
                            IR按键表
*******************************************************************/
#define IRFF00_IDLE_KEY_SHORT			\
	/*00*/	  NO_MSG,\
	/*01*/	  MSG_STANBY_KEY,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 MSG_STANBY_KEY
#define IRFF00_IDLE_KEY_LONG			\
	/*00*/	  NO_MSG,\
	/*01*/	  NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG

#define IRFF00_IDLE_KEY_HOLD			\
	/*00*/	  NO_MSG,\
	/*01*/    NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/    NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
	/*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG


#define IRFF00_IDLE_KEY_LONG_UP 		\
	/*00*/	  NO_MSG,\
	/*01*/	NO_MSG,\
	/*02*/	  NO_MSG,\
	/*03*/	  NO_MSG,\
	/*04*/	  NO_MSG,\
	/*05*/	  NO_MSG,\
	/*06*/	  NO_MSG,\
	/*07*/	  NO_MSG,\
	/*08*/	  NO_MSG,\
	/*09*/	  NO_MSG,\
	/*10*/	  NO_MSG,\
	/*11*/	  NO_MSG,\
	/*12*/	  NO_MSG,\
	/*13*/	  NO_MSG,\
	/*14*/	  NO_MSG,\
	/*15*/	  NO_MSG,\
	/*16*/	  NO_MSG,\
	/*17*/	  NO_MSG,\
	/*18*/	  NO_MSG,\
	/*19*/	  NO_MSG,\
	/*20*/	  NO_MSG,\
    /*21*/	 NO_MSG,\
	/*22*/	 NO_MSG,\
	/*23*/	 NO_MSG,\
	/*24*/	 NO_MSG,\
	/*25*/	 NO_MSG




