ifeq ($(CPU),bt15)

obj_S = \
 
objs = \
   a2dp/a2dp.o \
   a2dp/avctp.o \
   a2dp/avctp_user.o \
   a2dp/avdtp.o \
   port/bt_configs.o \
   port/database_file.o \
   port/h4_transport.o \
   port/hciattach_bt.o \
   port/a2dp_media_file.o \
   port/spp_accel.o \
   src/btstack_memory.o \
   src/hci.o \
   src/hci_cmds.o \
   src/hci_dump.o \
   src/hfp_profile.o \
   src/hid.o \
   src/l2cap.o \
   src/l2cap_signaling.o \
   src/linked_list.o \
   src/memory_pool.o \
   src/remote_device_db_memory.o \
   src/rfcomm.o \
   src/sdp.o \
   src/sdp_master.o \
   src/sdp_util.o \
   src/spp_profile.o \
   src/utils.o \
 
includes += \

 
CONFIG_LIB=n
-include ../rule.mk

endif 

